blank_issues_enabled: false
contact_links:
  - name: Email
    url: vijaybalaji2477@gmail.com
    about: Feel free to contact me for any reason related to the project.
contact_links:
  - name: Email
    url: osc@vitap.ac.in
    about: Contact current OSC admin team.